#! /usr/bin/env bash

## Color variables used later int the script
## Used in cecho function
bold='\033[1m'
origin='\033[0m'
black='\E[30;1m'
red='\E[31;1m'
green='\E[32;1m'
yellow='\E[33;1m'
blue='\E[34;1m'
magenta='\E[35;1m'
cyan='\E[36;1m'
white='\E[37;1m'


## Puts a cutt off
cut_off="------------------------------------------------------------------------"

## Echoes text with color output
## $1: message
## $2: color
cecho() {
    echo -e "${2:-${bold}}${1}"
    tput sgr0 # Reset to normal.
}

## Echoes text with red color 
## Function to print out error
put_error() {
    cecho "ERROR: $1" $red
}

## Function to exit the code with message
exit_with_msg() {
    cecho "$1" $red
    exit 1
}

## Function to print out debug information
## Color is set to magenta
info_msg() {
    echo "########################################################################"
    cecho "INFO: $1" $magenta
    echo "########################################################################"
}
## Function to print out warning to the user
warn() {
    cecho "$1" $yellow
}

## Sets path for the pacman configuration file
pacman_conf=/etc/pacman.conf

## Function for checking if the user is root
no_root() {
    if [[ $USER = 'root' ]]; then
        echo "Do not use root."
        exit 1
    fi
}

## puts a cuttoff with formatting
put_cutoff() {
    _line="\n${cut_off}\n"
    cecho $_line $cyan
    if [[ -n "$1" ]]; then
        echo -e "$1"
        cecho $_line $cyan
    fi
}

## Installs a set of packages
## The parameter must be a list where the packages are stored
do_install() {
    sudo pacman -S --needed --noconfirm "$@"
}

## function for selecting a option 

select_option() {
    put_cutoff
    local msg=$1 && shift
    local tmp_array=($@)
    local length=${#tmp_array[@]}
    local sequence=$(seq -s " " 00 $length)
    cecho "$msg :"
    for ((i = 0; i < $length; i++)); do # Used to display each option with index in the tmp_array list
        echo "$i>    ${tmp_array[$i]}"  # Printing the actual option
    done
    check_input "${sequence}" ans
    put_cutoff
}

# Display an array as options
# $1 array
# reutrns the index of the item selected by the user

# enhanced `read` - name a range for checking
# $1 input range, e.g. 123 Yn abcd (case insensitive)
# $2 variable's name check_input() {local _range=$1
check_input() {
    local _range=$1
    local is_valid=no
    local _default=${_range:0:1} # Initializes _default with the first character of the _range
    while [[ $is_valid = 'no' ]]; do
        read -p "Input: " ans
        [[ -z "$ans" ]] && ans=$_default # [[ -z "$ans" ]] checks if the variable is empty
        ans=$(echo $ans | tr '[A-Z]' '[a-z]') # Converts values of ans variable to lower case
        if [[ "$_range" = *$ans* ]]; then
            is_valid=yes
        else
            put_error "Valid answer: $_range (default=$_default):"
        fi
    done

    [[ -n $2 ]] && read $2 <<<$ans # Here $ans is fed into the read statement the whatever that is stored in $ans gets assigned to variable name that is $2 ## Very useful for automating input and creating varibales within the program

}

# -----------------------------------------------------------------------------
# basic
# -----------------------------------------------------------------------------

logo() {
    put_cutoff
    cecho "
   ▄████████    ▄████████  ▄████████    ▄█    █▄     ▄█  ███▄▄▄▄      ▄████████
  ███    ███   ███    ███ ███    ███   ███    ███   ███  ███▀▀▀██▄   ███    ███
  ███    ███   ███    ███ ███    █▀    ███    ███   ███▌ ███   ███   ███    █▀
  ███    ███  ▄███▄▄▄▄██▀ ███         ▄███▄▄▄▄███▄▄ ███▌ ███   ███   ███
▀███████████ ▀▀███▀▀▀▀▀   ███        ▀▀███▀▀▀▀███▀  ███▌ ███   ███ ▀███████████
  ███    ███ ▀███████████ ███    █▄    ███    ███   ███  ███   ███          ███
  ███    ███   ███    ███ ███    ███   ███    ███   ███  ███   ███    ▄█    ███
  ███    █▀    ███    ███ ████████▀    ███    █▀    █▀    ▀█   █▀   ▄████████▀
               ███    ███                                                       " $bold
    echo
}

## Optimizes pacman for its best performance
pacman_optimize() {  iso=$(curl -4 ifconfig.co/country-iso)
    pacman -Syy
    local pkgs=("pacman-contrib" "reflector")
    do_install "${pkgs[@]}"

    # Enabling parallel downloads
    sed -i 's/^#ParallelDownloads/ParallelDownloads/' /etc/pacman.conf
    cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.BAK
    info_msg "Paralell downloads for pacman has been enabled"
    reflector -a 48 -f 5 -l 20 --download-timeout 15 --sort rate --save /etc/pacman.d/mirrorlist
    info_msg "fastest mirrors has been set"
}
